# Generated by Django 4.2.14 on 2024-08-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_remove_blogs_color_remove_drafts_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='text',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='drafts',
            name='text',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
