# Generated by Django 4.2.14 on 2024-08-06 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_alter_blogs_text_alter_drafts_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 8, 8, 55, 786594, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='drafts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 8, 8, 55, 787494, tzinfo=datetime.timezone.utc)),
        ),
    ]
