# Generated by Django 4.2.14 on 2024-08-30 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_alter_blogs_date_alter_blogs_id_alter_drafts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 30, 8, 9, 3, 177145, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='drafts',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 30, 8, 9, 3, 178291, tzinfo=datetime.timezone.utc)),
        ),
    ]
