# Generated by Django 4.2.14 on 2024-08-30 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_alter_blogs_date_alter_drafts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 8, 9, 39, 413431, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='drafts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 8, 9, 39, 414252, tzinfo=datetime.timezone.utc)),
        ),
    ]
