# Generated by Django 4.2.14 on 2024-08-30 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0008_alter_blogs_date_alter_drafts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='uname',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='drafts',
            name='uname',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 18, 45, 16, 566007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='drafts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 18, 45, 16, 566530, tzinfo=datetime.timezone.utc)),
        ),
    ]
