# Generated by Django 4.2.14 on 2024-09-01 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0009_blogs_uname_drafts_uname_alter_blogs_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 7, 0, 0, 298539, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='drafts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 7, 0, 0, 299144, tzinfo=datetime.timezone.utc)),
        ),
    ]
