# Generated by Django 4.2.14 on 2024-09-01 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0010_alter_blogs_date_alter_drafts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='thumb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drafts',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drafts',
            name='thumb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 19, 59, 131728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='drafts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 19, 59, 132567, tzinfo=datetime.timezone.utc)),
        ),
    ]
