# Generated by Django 4.2.14 on 2024-09-01 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0011_blogs_like_blogs_thumb_drafts_like_drafts_thumb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drafts',
            name='like',
        ),
        migrations.RemoveField(
            model_name='drafts',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 41, 28, 651418, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='drafts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 41, 28, 652302, tzinfo=datetime.timezone.utc)),
        ),
    ]
