# Generated by Django 4.2.14 on 2024-09-01 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0012_remove_drafts_like_remove_drafts_thumb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='thumbdown',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 55, 51, 537963, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='drafts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 55, 51, 539159, tzinfo=datetime.timezone.utc)),
        ),
    ]
