# Generated by Django 4.2.14 on 2024-09-01 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0013_blogs_thumbdown_alter_blogs_date_alter_drafts_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='thumbdown',
            new_name='dislike',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='thumb',
        ),
        migrations.AddField(
            model_name='blogs',
            name='love',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 19, 11, 56, 679527, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='drafts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 19, 11, 56, 680753, tzinfo=datetime.timezone.utc)),
        ),
    ]
