# Generated by Django 4.2.14 on 2024-09-01 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0014_rename_thumbdown_blogs_dislike_remove_blogs_thumb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 19, 18, 28, 518149, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='drafts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 19, 18, 28, 518738, tzinfo=datetime.timezone.utc)),
        ),
    ]
